language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t waffoluc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true waffoluc/docker-react npm run test